name: Release dotnet project

on:
  workflow_call:
    inputs:
      deploy_env:
        description: Deployment environment (prod, stag or dev)
        required: true
        type: string
      
      package_version:
        description: Package version
        required: true
        type: string

jobs:
  build-and-release-cli:
    if: inputs.deploy_env == 'prod' || inputs.deploy_env == 'stag'
    runs-on: ubuntu-latest

    environment: ${{ inputs.deploy_env }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate CLI package version
        id: validate-version
        env:
          DEPLOY_ENV: ${{ inputs.deploy_env }}
          PACKAGE_VERSION: ${{ inputs.package_version }}
        run: |
          if git rev-parse "refs/tags/$PACKAGE_VERSION" >/dev/null 2>&1; then
              echo "Tag $PACKAGE_VERSION already exists."
              echo "VERSION_CHANGE=false" >> $GITHUB_OUTPUT
          else 
              echo "Tag $PACKAGE_VERSION does not exists."
              echo "VERSION_CHANGE=true" >> $GITHUB_OUTPUT
          fi
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore project dependencies
        run: dotnet restore

      - name: Build and zip the project for Windows
        run: |
          dotnet publish src/Chirp.CLI -c Release -r win-x64 --self-contained -o chirp-cli-win-x64
          zip -r chirp-cli-win-x64.zip chirp-cli-win-x64

      - name: Build and zip the project for Linux
        run: |
          dotnet publish src/Chirp.CLI -c Release -r linux-x64 --self-contained -o chirp-cli-linux-x64
          zip -r chirp-cli-linux-x64.zip chirp-cli-linux-x64

      - name: Build and zip the project for MacOS
        run: |
          dotnet publish src/Chirp.CLI -c Release -r osx-x64 --self-contained -o chirp-cli-osx-x64
          zip -r chirp-cli-osx-x64.zip chirp-cli-osx-x64

      - name: Archive the CLI packages
        uses: actions/upload-artifact@v4
        with:
          name: chirp-cli
          path: |
            chirp-cli-win-x64.zip 
            chirp-cli-linux-x64.zip 
            chirp-cli-osx-x64.zip 
      
      - name: Create a GitHub release
        if: steps.validate-version.outputs.VERSION_CHANGE == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.package_version }}
          prerelease: ${{ inputs.deploy_env == 'stag' }}
          files: |
            chirp-cli-win-x64.zip 
            chirp-cli-linux-x64.zip 
            chirp-cli-osx-x64.zip
