name: Release dotnet project

on:
  workflow_call:
    inputs:
      deploy_env:
        description: Deployment environment (prod, stag or dev)
        required: true
        type: string
      
      package_version:
        description: Package version
        required: true
        type: string

jobs:
  release-cli:
    if: inputs.deploy_env == 'prod' || inputs.deploy_env == 'stag'
    runs-on: ubuntu-latest

    environment: ${{ inputs.deploy_env }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Validate package version
        env:
          PACKAGE_VERSION: ${{ inputs.package_version }}
        run: |
          if git rev-parse "refs/tags/$PACKAGE_VERSION" >/dev/null 2>&1; then
            echo "Tag $PACKAGE_VERSION already exists."
            exit 1
          fi
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and zip the project for windows
        run: |
          dotnet publish src/Chirp.CLI -c Release -r win-x64 --self-contained -o chirp-cli-win-x64
          zip -r chirp-cli-win-x64.zip chirp-cli-win-x64

      - name: Build and zip the project for linux
        run: |
          dotnet publish src/Chirp.CLI -c Release -r linux-x64 --self-contained -o chirp-cli-linux-x64
          zip -r chirp-cli-linux-x64.zip chirp-cli-linux-x64

      - name: Build and zip the project for macos
        run: |
          dotnet publish src/Chirp.CLI -c Release -r osx-x64 --self-contained -o chirp-cli-osx-x64
          zip -r chirp-cli-osx-x64.zip chirp-cli-osx-x64

      - name: Archive the project
        uses: actions/upload-artifact@v4
        with:
          path: |
            chirp-cli-win-x64.zip 
            chirp-cli-linux-x64.zip 
            chirp-cli-osx-x64.zip 
      
      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.package_version }}
          prerelease: ${{ inputs.deploy_env == 'stag' }}
          files: |
            chirp-cli-win-x64.zip 
            chirp-cli-linux-x64.zip 
            chirp-cli-osx-x64.zip
