name: Deploy service to Azure

on:
  workflow_dispatch:
    inputs:
      deploy_platform:
        description: Deployment platform (e.g. azure, flyio...)
        required: true
        type: string

      deploy_env:
        description: Deployment environment (prod, stag or dev)
        required: true
        type: string

jobs:
  deploy-csv-database-web-service:
    if: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4