name: Lint and test a .NET project

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: The version of .NET to use
        required: true
        type: string

      deploy_env:
        description: Deployment environment (prod, stag or dev)
        required: true
        type: string

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Chirp.Web user-secrets
        run: |
          dotnet user-secrets set "GH_CLIENT_ID" ${{ secrets.GH_CLIENT_ID }} --project ./src/Chirp.Web
          dotnet user-secrets set "GH_CLIENT_SECRET" ${{ secrets.GH_CLIENT_SECRET }} --project ./src/Chirp.Web

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore

  test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Chirp.Web user-secrets
        run: |
          dotnet user-secrets set -c Debug "GitHub:ClientId" ${{ secrets.GH_CLIENT_ID }} --project ./src/Chirp.Web
          dotnet user-secrets set -c Debug "GitHub:ClientSecret" ${{ secrets.GH_CLIENT_SECRET }} --project ./src/Chirp.Web

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore

      - name: Test the project
        run: dotnet test --no-build

  lint-solution:
    runs-on: ubuntu-latest

    needs: [test-linux, test-windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore

    - name: Lint the project
      run: dotnet format --no-restore
