name: CI/CD pipeline for a .NET project

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  prepare-pipeline:
    uses: ./.github/workflows/prepare-pipeline.yml
    secrets: inherit

  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    needs: [prepare-pipeline]
    secrets: inherit
    with:
      deploy_env: ${{ needs.prepare-pipeline.outputs.deploy_env }}

  build-and-release:
    uses: ./.github/workflows/build-and-release.yml
    needs: [prepare-pipeline, lint-and-test]
    secrets: inherit
    with:
      deploy_env: ${{ needs.prepare-pipeline.outputs.deploy_env }}
