name: CI/CD pipeline for our Chirp project

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - test/**
      - Chrip.sln
      - VERSION
    branches:
      - '**'

jobs:
  prepare-pipeline:
    uses: ./.github/workflows/prepare-pipeline.yml
    secrets: inherit

  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    needs: [prepare-pipeline]
    secrets: inherit
    with:
      dotnet_version: ${{ needs.prepare-pipeline.outputs.dotnet_version }}
      deploy_env: ${{ needs.prepare-pipeline.outputs.deploy_env }}

  build-and-release:
    uses: ./.github/workflows/build-and-release.yml
    needs: [prepare-pipeline, lint-and-test]
    secrets: inherit
    with:
      dotnet_version: ${{ needs.prepare-pipeline.outputs.dotnet_version }}
      deploy_env: ${{ needs.prepare-pipeline.outputs.deploy_env }}
      solution_version: ${{ needs.prepare-pipeline.outputs.solution_version }}

  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    needs: [prepare-pipeline, lint-and-test]
    secrets: inherit
    with:
      dotnet_version: ${{ needs.prepare-pipeline.outputs.dotnet_version }}
      deploy_env: ${{ needs.prepare-pipeline.outputs.deploy_env }}

  build-and-deploy-docs:
    uses: ./.github/workflows/build-and-deploy-docs.yml
    needs: [prepare-pipeline, lint-and-test]
    secrets: inherit
    with:
      deploy_env: ${{ needs.prepare-pipeline.outputs.deploy_env }}
