name: CI/CD pipeline our a .NET project

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - test/**
      - Chrip.sln
    branches:
      - '**'

jobs:
  prepare-pipeline:
    uses: ./.github/workflows/prepare-pipeline.yml
    secrets: inherit

  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    needs: [prepare-pipeline]
    secrets: inherit
    with:
      deploy_env: ${{ needs.prepare-pipeline.outputs.deploy_env }}

  build-and-release:
    uses: ./.github/workflows/build-and-release.yml
    needs: [prepare-pipeline, lint-and-test]
    secrets: inherit
    with:
      deploy_env: ${{ needs.prepare-pipeline.outputs.deploy_env }}
      package_version: ${{ needs.prepare-pipeline.outputs.package_version }}
  
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    needs: [prepare-pipeline, lint-and-test]
    secrets: inherit
    with:
      deploy_env: ${{ needs.prepare-pipeline.outputs.deploy_env }}
