name: Pipline for our pull requests

on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  prepare-pipeline:
    uses: ./.github/workflows/prepare-pipeline.yml
    secrets: inherit

  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    needs: [prepare-pipeline]
    secrets: inherit
    with:
      deploy_env: ${{ needs.prepare-pipeline.outputs.deploy_env }}
